DROP TABLE IF EXISTS conditions CASCADE;
DROP TABLE IF EXISTS professions CASCADE;
DROP TABLE IF EXISTS crew_members CASCADE;
DROP TABLE IF EXISTS type_of_system CASCADE;
DROP TABLE IF EXISTS type_of_dang CASCADE;
DROP TABLE IF EXISTS type_of_hp CASCADE;
DROP TABLE IF EXISTS systems CASCADE;
DROP TABLE IF EXISTS members_to_system CASCADE;